## KHÁM PHÁ DỮ LIỆU

### 1. Đọc dữ liệu, tính số dòng và cột

Đầu tiên, ta import các thư viện cần thiết.

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# .. import more libraries

Tiếp đến đọc các file điểm thi của các năm và lưu vào các dataframe tương ứng. Sau đó in ra 5 dòng đầu tiên.

In [6]:
grade_df = {}
grade_df['2020'] = pd.read_csv('data/diemthi2020_final.csv')
grade_df['2020'].head()

,Unnamed: 0,SBD,Tỉnh/Thành phố,Toán,Văn,Lí,Hóa,Sinh,TB-KHTN,Sử,Địa,GDCD,TB-KHXH,Ngoại ngữ
0,0,18014547,BẮC GIANG,6.4,6.75,NaN,NaN,NaN,NaN,4.75,7.00,6.50,6.08,4.2
1,1,18014530,BẮC GIANG,7.6,6.00,NaN,NaN,NaN,NaN,3.75,7.75,7.75,6.42,2.8
2,2,18014521,BẮC GIANG,4.8,4.75,NaN,NaN,NaN,NaN,4.00,6.50,NaN,5.25,NaN
3,3,18014517,BẮC GIANG,8.0,7.00,NaN,NaN,NaN,NaN,8.25,8.00,9.50,8.58,5.8
4,4,18014523,BẮC GIANG,8.2,6.50,8.0,8.5,5.0,7.17,NaN,NaN,NaN,NaN,4.0

In [7]:
grade_df['2021'] = pd.read_csv('data/diemthi2021_final.csv')
grade_df['2021'].head()

,Unnamed: 0,SBD,Toán,Văn,Ngoại ngữ,Lí,Hóa,Sinh,Sử,Địa,GDCD,Tỉnh/Thành phố,TB-KHTN,TB-KHXH
0,0,1000001,3.6,5.00,4.0,NaN,NaN,NaN,2.75,6.0,8.75,HÀ NỘI,NaN,5.83
1,1,1000002,8.4,6.75,7.6,NaN,NaN,NaN,8.50,7.5,8.25,HÀ NỘI,NaN,8.08
2,2,1000003,5.8,7.50,5.0,NaN,NaN,NaN,7.25,5.5,8.75,HÀ NỘI,NaN,7.17
3,3,1000004,7.4,7.50,8.6,NaN,NaN,NaN,7.50,6.5,7.50,HÀ NỘI,NaN,7.17
4,4,1000005,7.2,8.50,9.0,NaN,NaN,NaN,8.00,8.5,8.25,HÀ NỘI,NaN,8.25

In [8]:
grade_df['2022'] = pd.read_csv('data/diemthi2022_final.csv')
grade_df['2022'].head()

,Unnamed: 0,SBD,Toán,Văn,Ngoại ngữ,Lí,Hóa,Sinh,Sử,Địa,GDCD,Tỉnh/Thành phố,TB-KHTN,TB-KHXH
0,0,1000001,3.6,5.00,4.0,NaN,NaN,NaN,2.75,6.0,8.75,HÀ NỘI,NaN,5.83
1,1,1000002,8.4,6.75,7.6,NaN,NaN,NaN,8.50,7.5,8.25,HÀ NỘI,NaN,8.08
2,2,1000003,5.8,7.50,5.0,NaN,NaN,NaN,7.25,5.5,8.75,HÀ NỘI,NaN,7.17
3,3,1000004,7.4,7.50,8.6,NaN,NaN,NaN,7.50,6.5,7.50,HÀ NỘI,NaN,7.17
4,4,1000005,7.2,8.50,9.0,NaN,NaN,NaN,8.00,8.5,8.25,HÀ NỘI,NaN,8.25

Tính số dòng, số cột và lưu vào 2 biến `n_rows` và `n_cols`.

In [9]:
n_rows = {}
n_cols = {}
for year in grade_df.keys():
    n_rows[year], n_cols[year] = grade_df[year].shape
    print(f'Number of rows in {year}: {n_rows[year]}')
    print(f'Number of columns in {year}: {n_cols[year]}')

Number of rows in 2020: 870486
Number of columns in 2020: 14
Number of rows in 2021: 995381
Number of columns in 2021: 14
Number of rows in 2022: 995441
Number of columns in 2022: 14

### 2. Mỗi dòng có ý nghĩa gì? Có vấn đề các dòng có ý nghĩa khác nhau không?

Mỗi dòng trong tập dữ liệu này tương ứng với điểm thi các môn của một thí sinh riêng biệt. Gồm các môn Toán, Ngữ Văn, Ngoại Ngữ, Vật Lý, Hóa Học, Sinh Học, Lịch Sử, Địa Lý, GDCD và điểm trung bình các tổ hợp môn.
Do vậy, ta có thể thấy rằng không có dòng nào bị "lạc loài".

### 3. Dữ liệu có các dòng bị lặp không?

Ta kiểm tra xem có dòng nào bị lặp không bằng cách sử dụng các phương `duplicated()` và `any()` trên các dataframe `grade_df` và lưu kết quả vào biến `have_duplicated_rows`. Biến này sẽ có giá trị `True` nếu dữ liệu có các dòng bị lặp và có giá trị `False` nếu ngược.

In [10]:
have_duplicate_rows = {}
for year in grade_df.keys():
    have_duplicate_rows[year] = grade_df[year].duplicated().any()
    print(f'Have duplicate rows in {year}: {have_duplicate_rows[year]}')

Have duplicate rows in 2020: False
Have duplicate rows in 2021: False
Have duplicate rows in 2022: False

Như vậy ta thấy rằng dữ liệu không có các dòng bị lặp.

### 4. Kiểu dữ liệu của mỗi cột

Ta sử dụng phương thức `dtypes` trên `grade_df` để xem kiểu dữ liệu của mỗi cột. Kết quả được lưu vào dataframe `col_dtypes`; dataframe này có tên dòng là các năm và tên cột là các cột trong `grade_df`.

In [11]:
col_dtypes = {}
for year in grade_df.keys():
    col_dtypes[year] = grade_df[year].dtypes
col_dtypes = pd.DataFrame(col_dtypes).T
col_dtypes

,GDCD,Hóa,Lí,Ngoại ngữ,SBD,Sinh,Sử,TB-KHTN,TB-KHXH,Toán,Tỉnh/Thành phố,Unnamed: 0,Văn,Địa
2020,float64,float64,float64,float64,int64,float64,float64,float64,float64,float64,object,int64,float64,float64
2021,float64,float64,float64,float64,int64,float64,float64,float64,float64,float64,object,int64,float64,float64
2022,float64,float64,float64,float64,int64,float64,float64,float64,float64,float64,object,int64,float64,float64

Có thể thấy, kiểu dữ liệu các cột ở ba năm đều giống nhau. Về mặt kiểu dữ liệu, các thuộc tính của tập dữ liệu này đã ở định dạng phù hợp, nên không cần phải xử lý.

### 5. Xem xét sự phân bố giá trị của các cột dữ liệu dạng số.

Ta cần xem xét đến các giá trị thiếu trong dữ liệu:
- Không thực hiện thống kê trên 3 cột SBD, Unnamed và Tỉnh/Thành phố do các cột này không có ý nghĩa và cột Tỉnh/Thành phố không phải dạng số và sẽ được xem xét sau.
- Đầu tiên, ta tính tỉ lệ giá trị thiếu của từng cột bằng cách sử dụng phương thức `isnull()` trên dataframe `grade_df` và tính tổng số giá trị thiếu của từng cột bằng phương thức `sum()`. 
- Cuối cùng ta chia số dòng và lưu kết quả vào `missing_ratio`.

In [12]:
missing_ratio = {}
for year in grade_df.keys():
    missing_ratio[year] = grade_df[year].select_dtypes(include=['float64']).isnull().sum() / n_rows[year]
missing_ratio = pd.DataFrame(missing_ratio).T
missing_ratio

,GDCD,Hóa,Lí,Ngoại ngữ,Sinh,Sử,TB-KHTN,TB-KHXH,Toán,Văn,Địa
2020,0.445161,0.660493,0.663077,0.113027,0.666420,0.346823,0.658150,0.346564,0.004486,0.015992,0.362342
2021,0.443112,0.671128,0.672979,0.125389,0.676320,0.337322,0.679848,0.443366,0.012770,0.014095,0.339572
2022,0.443118,0.671134,0.672986,0.125404,0.676326,0.337317,0.679855,0.443372,0.012773,0.014098,0.339568

Có thể thấy, các cột phân loại như `SBD`, `Tỉnh/Thành phố`, `Unnamed` (tương ứng với số thứ tự) đều có tỉ lệ giá trị thiếu là 0. Các cột còn lại đều là cột điểm thi và có tỉ lệ giá trị thiếu khác 0. Điều này cho thấy rằng có một số thí sinh không thi một số môn nào đó và không ảnh hưởng đến việc phân tích sau này.

Ta cũng cần tính các giá trị thống kê mô tả của các cột numeric bằng phương thức `describe()` trên `grade_df`.

In [13]:
print(f'Descriptive statistics of 2020:')
grade_df['2020'].describe()

Descriptive statistics of 2020:

,Unnamed: 0,SBD,Toán,Văn,Lí,Hóa,Sinh,TB-KHTN,Sử,Địa,GDCD,TB-KHXH,Ngoại ngữ
count,870486.00000,8.704860e+05,866581.000000,856565.000000,293287.000000,295536.000000,290377.000000,297576.000000,568581.000000,555072.000000,482980.000000,568807.000000,772098.000000
mean,435242.50000,2.800845e+07,6.662271,6.601825,6.718001,6.705225,5.588041,6.341871,5.181097,6.773215,8.125164,6.549127,4.568337
std,251287.80755,1.898843e+07,1.819042,1.248463,1.497900,1.607924,1.350572,1.109016,1.598987,1.171702,1.090310,1.215503,1.808446
min,0.00000,1.000001e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,217621.25000,1.200657e+07,5.400000,6.000000,5.750000,5.500000,4.750000,5.670000,4.000000,6.000000,7.500000,5.830000,3.200000
50%,435242.50000,2.801803e+07,7.000000,6.750000,7.000000,7.000000,5.500000,6.500000,5.000000,7.000000,8.250000,6.580000,4.200000
75%,652863.75000,4.400927e+07,8.000000,7.500000,7.750000,8.000000,6.500000,7.170000,6.250000,7.500000,9.000000,7.380000,5.600000
max,870485.00000,6.400582e+07,10.000000,10.000000,10.000000,10.000000,10.000000,9.880000,10.000000,10.000000,10.000000,10.000000,10.000000

In [14]:
print(f'Descriptive statistics of 2021:')
grade_df['2021'].describe()

Descriptive statistics of 2021:

,Unnamed: 0,SBD,Toán,Văn,Ngoại ngữ,Lí,Hóa,Sinh,Sử,Địa,GDCD,TB-KHTN,TB-KHXH
count,995381.000000,9.953810e+05,982670.000000,981351.000000,870571.000000,325510.000000,327353.000000,322185.000000,659617.000000,657377.000000,554316.000000,318673.000000,554063.000000
mean,497690.000000,2.759687e+07,6.466307,6.507771,5.157718,6.723776,6.703872,5.019119,6.343983,6.677960,8.033279,6.137007,7.088267
std,287341.888486,1.917116e+07,1.675402,1.379598,1.949552,1.441914,1.600390,1.448270,1.612875,1.214998,1.067257,1.102181,1.086869
min,0.000000,1.000001e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.080000
25%,248845.000000,1.000216e+07,5.400000,5.580000,3.600000,5.750000,5.500000,4.000000,5.250000,5.750000,7.500000,5.420000,6.420000
50%,497690.000000,2.801888e+07,6.800000,6.500000,4.800000,7.000000,7.000000,4.750000,6.500000,6.750000,8.250000,6.250000,7.170000
75%,746535.000000,4.400583e+07,7.800000,7.500000,6.600000,7.750000,8.000000,6.000000,7.500000,7.500000,8.750000,6.920000,7.830000
max,995380.000000,6.400659e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.670000,10.000000

In [15]:
print(f'Descriptive statistics of 2022:')
grade_df['2022'].describe()

Descriptive statistics of 2022:

,Unnamed: 0,SBD,Toán,Văn,Ngoại ngữ,Lí,Hóa,Sinh,Sử,Địa,GDCD,TB-KHTN,TB-KHXH
count,995441.000000,9.954410e+05,982726.000000,981407.000000,870609.000000,325523.000000,327367.000000,322198.000000,659662.000000,657421.000000,554343.000000,318685.000000,554090.000000
mean,497720.000000,2.759692e+07,6.466254,6.507746,5.157686,6.723779,6.703898,5.019109,6.343930,6.677929,8.033266,6.137013,7.088246
std,287359.208994,1.917092e+07,1.675435,1.379602,1.949547,1.441925,1.600393,1.448270,1.612879,1.215013,1.067272,1.102178,1.086883
min,0.000000,1.000001e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.080000
25%,248860.000000,1.000217e+07,5.400000,5.580000,3.600000,5.750000,5.500000,4.000000,5.250000,5.750000,7.500000,5.420000,6.420000
50%,497720.000000,2.801886e+07,6.800000,6.500000,4.800000,7.000000,7.000000,4.750000,6.500000,6.750000,8.250000,6.250000,7.170000
75%,746580.000000,4.400582e+07,7.800000,7.500000,6.600000,7.750000,8.000000,6.000000,7.500000,7.500000,8.750000,6.920000,7.830000
max,995440.000000,6.400659e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.670000,10.000000

### 6. Xem xét sự phân bố giá trị của các cột dữ liệu không phải dạng số.

Trong 3 bộ dữ liệu về điểm thi của cả 3 năm thì chỉ có duy nhất cột 'Tỉnh/Thành phố' là cột có kiểu dữ liệu không phải dạng số.

**Nhận xét:** Do cột 'Tỉnh/Thành phố' có thể được suy ra từ SBD của thí sinh, do đó có thể rút ra một số nhận xét sau:
- Không tồn tại giá trị thiếu trong cột 'Tỉnh/Thành phố' do tương ứng với mỗi thí sinh trong bộ dữ liệu đều sẽ suy ra được mã tỉnh.
- Số lượng các giá trị khác nhau của cột này cũng sẽ bằng 63, chính là 63 tỉnh thành trên đất nước Việt Nam (tuy mã tỉnh lớn nhất là 64 nhưng không có mã tỉnh 20, nên tương ứng chỉ có 63 tỉnh thành).
- Ta sẽ thực hiện tính tỉ lệ % (từ 0 đến 100) của mỗi giá trị khác nhau trong cột 'Tỉnh/Thành phố' được sort theo tỉ lệ % giảm dần (không xét giá trị thiếu, tỉ lệ là tỉ lệ so với số lượng các giá trị không thiếu): dùng dictionary để lưu, key là giá trị, value là tỉ lệ % (value_ratios). Sau đó lưu vào DataFrame với dòng là value_ratios và cột tương ứng là 3 năm từ 2020 đến 2022. 
- Viết hàm 'computeValueRatios' nhận vào một DataFrame dữ liệu của một năm và trả về dictionary lưu value_ratios cần tính đã trình bày ở trên của năm đó.
- Sau khi có được ba dictionary cho ba năm, dùng chúng tạo thành một DataFrame.

In [16]:
def computeValueRatios(df):
    col_name='Tỉnh/Thành phố'
    df=df.copy()
    df=df.select_dtypes(exclude=['float64','int64'])
    vals=list(df[col_name].values)
    num_vals=list(set(vals))
    dic={}
    new=[(df[col_name].value_counts()[j]/len(vals)*100).round(3) for j in num_vals]
    dic={num_vals[j]:new[j] for j in range(len(num_vals))}
    dic_sort={k:v for k,v in sorted(dic.items(), key= lambda item:item[1], reverse=True)}
    return dic_sort

In [17]:
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
col_names=['2020','2021','2022']
titles=["value_ratios"]
values_list=[computeValueRatios(grade_df[f'{i}']) for i in range(2020,2023)]
dic={col_names[i]:[values_list[i]] for i in range(len(col_names))}
dic['titles']=titles
categorical_info_df=pd.DataFrame(dic).set_index('titles')
categorical_info_df

C:\Users\FPT SHOP\AppData\Local\Temp\ipykernel_8460\4207576729.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

,2020,2021,2022
titles,,,
value_ratios,"{'HÀ NỘI': 9.059, 'HỒ CHÍ MINH': 8.553, 'THANH HÓA': 3.991, 'NGHỆ AN': 3.57, 'ĐỒNG NAI': 3.246, 'THÁI BÌNH': 2.251, 'HẢI DƯƠNG': 2.25, 'BẮC GIANG': 2.217, 'NAM ĐỊNH': 2.144, 'HẢI PHÒNG': 2.129, 'BÌNH ĐỊNH': 1.939, 'HÀ TĨNH': 1.759, 'AN GIANG': 1.751, 'THÁI NGUYÊN': 1.745, 'BẮC NINH': 1.68, 'QUẢNG NINH': 1.671, 'TIỀN GIANG': 1.641, 'ĐẮK LẮK': 1.602, 'LONG AN': 1.591, 'PHÚ THỌ': 1.586, 'LÂM ĐỒNG': 1.551, 'ĐỒNG THÁP': 1.538, 'GIA LAI': 1.53, 'KHÁNH HÒA': 1.504, 'HƯNG YÊN': 1.468, 'THỪA THIÊN - HUẾ': 1.438, 'KIÊN GIANG': 1.428, 'VĨNH PHÚC': 1.398, 'QUẢNG NGÃI': 1.375, 'SƠN LA': 1.336, 'BÀ RỊA – VŨNG TÀU': 1.314, 'BÌNH DƯƠNG': 1.308, 'BẾN TRE': 1.3, 'BÌNH THUẬN': 1.251, 'QUẢNG BÌNH': 1.224, 'CẦN THƠ': 1.223, 'VĨNH LONG': 1.173, 'PHÚ YÊN': 1.158, 'BÌNH PHƯỚC': 1.123, 'CÀ MAU': 1.107, 'NINH BÌNH': 1.059, 'HÒA BÌNH': 1.051, 'HÀ NAM': 0.985, 'TÂY NINH': 0.982, 'LẠNG SƠN': 0.978, 'SÓC TRĂNG': 0.978, 'TUYÊN QUANG': 0.918, 'QUẢNG TRỊ': 0.907, 'TRÀ VINH': 0.906, 'YÊN BÁI': 0.851, 'QUẢNG NAM': 0.836, 'LÀO CAI': 0.73, 'ĐĂK NÔNG': 0.714, 'HẬU GIANG': 0.668, 'NINH THUẬN': 0.657, 'HÀ GIANG': 0.646, 'ĐIỆN BIÊN': 0.644, 'BẠC LIÊU': 0.642, 'CAO BẰNG': 0.528, 'KON TUM': 0.493, 'LAI CHÂU': 0.379, 'BẮC KẠN': 0.328}","{'HÀ NỘI': 9.739, 'HỒ CHÍ MINH': 8.499, 'THANH HÓA': 3.764, 'NGHỆ AN': 3.673, 'ĐỒNG NAI': 3.151, 'HẢI PHÒNG': 2.25, 'BẮC GIANG': 2.065, 'HẢI DƯƠNG': 2.052, 'ĐẮK LẮK': 2.044, 'THÁI BÌNH': 2.024, 'NAM ĐỊNH': 1.986, 'AN GIANG': 1.866, 'BÌNH ĐỊNH': 1.857, 'HÀ TĨNH': 1.738, 'QUẢNG NAM': 1.682, 'BẮC NINH': 1.592, 'PHÚ THỌ': 1.588, 'QUẢNG NINH': 1.57, 'LONG AN': 1.539, 'THÁI NGUYÊN': 1.515, 'ĐỒNG THÁP': 1.511, 'TIỀN GIANG': 1.51, 'KIÊN GIANG': 1.439, 'LÂM ĐỒNG': 1.417, 'GIA LAI': 1.414, 'KHÁNH HÒA': 1.409, 'HƯNG YÊN': 1.395, 'VĨNH PHÚC': 1.394, 'QUẢNG NGÃI': 1.336, 'THỪA THIÊN - HUẾ': 1.336, 'BÌNH DƯƠNG': 1.286, 'BÌNH THUẬN': 1.279, 'BÀ RỊA – VŨNG TÀU': 1.272, 'ĐÀ NẴNG': 1.263, 'BẾN TRE': 1.236, 'CẦN THƠ': 1.225, 'SƠN LA': 1.138, 'QUẢNG BÌNH': 1.117, 'PHÚ YÊN': 1.092, 'BÌNH PHƯỚC': 1.075, 'CÀ MAU': 1.074, 'NINH BÌNH': 1.055, 'VĨNH LONG': 1.037, 'SÓC TRĂNG': 1.003, 'TÂY NINH': 0.981, 'LẠNG SƠN': 0.965, 'HÒA BÌNH': 0.959, 'TRÀ VINH': 0.95, 'HÀ NAM': 0.923, 'QUẢNG TRỊ': 0.868, 'TUYÊN QUANG': 0.846, 'YÊN BÁI': 0.808, 'LÀO CAI': 0.724, 'ĐĂK NÔNG': 0.688, 'HẬU GIANG': 0.658, 'ĐIỆN BIÊN': 0.644, 'BẠC LIÊU': 0.644, 'NINH THUẬN': 0.59, 'HÀ GIANG': 0.589, 'CAO BẰNG': 0.507, 'KON TUM': 0.475, 'LAI CHÂU': 0.368, 'BẮC KẠN': 0.307}","{'HÀ NỘI': 9.739, 'HỒ CHÍ MINH': 8.498, 'THANH HÓA': 3.764, 'NGHỆ AN': 3.673, 'ĐỒNG NAI': 3.151, 'HẢI PHÒNG': 2.25, 'BẮC GIANG': 2.065, 'HẢI DƯƠNG': 2.052, 'ĐẮK LẮK': 2.044, 'THÁI BÌNH': 2.024, 'NAM ĐỊNH': 1.986, 'AN GIANG': 1.866, 'BÌNH ĐỊNH': 1.857, 'HÀ TĨNH': 1.738, 'QUẢNG NAM': 1.682, 'BẮC NINH': 1.592, 'PHÚ THỌ': 1.588, 'QUẢNG NINH': 1.57, 'LONG AN': 1.539, 'THÁI NGUYÊN': 1.515, 'ĐỒNG THÁP': 1.511, 'TIỀN GIANG': 1.51, 'KIÊN GIANG': 1.439, 'LÂM ĐỒNG': 1.417, 'GIA LAI': 1.414, 'KHÁNH HÒA': 1.409, 'HƯNG YÊN': 1.395, 'VĨNH PHÚC': 1.394, 'QUẢNG NGÃI': 1.336, 'THỪA THIÊN - HUẾ': 1.336, 'BÌNH DƯƠNG': 1.286, 'BÌNH THUẬN': 1.279, 'BÀ RỊA – VŨNG TÀU': 1.272, 'ĐÀ NẴNG': 1.263, 'BẾN TRE': 1.236, 'CẦN THƠ': 1.225, 'SƠN LA': 1.138, 'QUẢNG BÌNH': 1.117, 'PHÚ YÊN': 1.092, 'BÌNH PHƯỚC': 1.075, 'CÀ MAU': 1.074, 'NINH BÌNH': 1.055, 'VĨNH LONG': 1.037, 'SÓC TRĂNG': 1.003, 'TÂY NINH': 0.981, 'LẠNG SƠN': 0.965, 'HÒA BÌNH': 0.962, 'TRÀ VINH': 0.95, 'HÀ NAM': 0.923, 'QUẢNG TRỊ': 0.868, 'TUYÊN QUANG': 0.846, 'YÊN BÁI': 0.808, 'LÀO CAI': 0.724, 'ĐĂK NÔNG': 0.688, 'HẬU GIANG': 0.658, 'ĐIỆN BIÊN': 0.644, 'BẠC LIÊU': 0.644, 'NINH THUẬN': 0.59, 'HÀ GIANG': 0.589, 'CAO BẰNG': 0.507, 'KON TUM': 0.475, 'LAI CHÂU': 0.368, 'BẮC KẠN': 0.307}"

**Nhận xét:**
- Số lượng các thí sinh thi của các tỉnh thành tham dự kì thi qua các năm luôn đông nhất ở 5 tỉnh thành lớn là: Hà Nội, Hồ Chí Minh, Thanh Hóa, Nghệ An, Đồng Nai.
- Những tỉnh thành đóng góp ít thí sinh nhất cho kì thi luôn là những nơi vùng cao như: Cao Bằng, Kon Tum, Lai Châu, Bắc Cạn.
- Số lượng thí sinh thi ở mỗi tỉnh qua các năm không chênh lệch nhau nhiều lắm cho thấy được sự ổn định của việc tốt nghiệp THPT ở các tỉnh thành.